In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("student.csv")
df_before = pd.read_csv("student.csv")

In [5]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [6]:
#ใช้วิธีแทนค่าว่างเปล่าด้วยการใช้ค่าเฉลี่ย
mean_age = df['อายุ'].mean()
df['อายุ'] = df['อายุ'].fillna(mean_age).astype(int)
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,28,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [7]:
#ใช้วิธีแทนค่าว่างเปล่าด้วยค่าที่พบบ่อย
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)
df

/tmp/ipython-input-180521225.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,28,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,28,NaN,Science,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21,หญิง,Science,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,28,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

In [8]:
def standardize_faculty(name):
    name = name.lower()
    if name in ['วิทยาศาสตร์', 'วิทย์', 'science', 'คณะวิทยาศาสตร์','sci']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'arts','liberal arts']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวฯ','วิศวกรรม','engineering','วิศวะ']:
        return 'วิศวกรรมศาสตร์'
    else:
        return name

df['คณะ'] = df['คณะ'].apply(standardize_faculty)
df['คณะ_มาตรฐาน'] = df['คณะ'].apply(standardize_faculty)
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
2,64003,NaN,28,Male,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ช,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,ญ,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์
5,64006,กานต์,150,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2023-12-23,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,M,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
10,64011,ธีระ,28,NaN,วิทยาศาสตร์,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,Female,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
18,64019,รัตนา,28,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์
19,64020,ลัดดา,22,NaN,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

In [9]:
#ใช้วิธีแทนค่าว่างเปล่าด้วยค่าที่พบบ่อย
df['เพศ'].fillna(df['เพศ'].mode()[0], inplace=True)
df

/tmp/ipython-input-2243611003.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['เพศ'].fillna(df['เพศ'].mode()[0], inplace=True)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
2,64003,NaN,28,Male,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ช,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,ญ,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์
5,64006,กานต์,150,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2023-12-23,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,M,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
10,64011,ธีระ,28,ชาย,วิทยาศาสตร์,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,Female,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
18,64019,รัตนา,28,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์
19,64020,ลัดดา,22,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

In [10]:
def standardize_gender(gender):
    gender = gender.lower()
    if gender in ['ญ','female','f']:
        return 'หญิง'
    elif gender in ['male','ช','m']:
        return 'ชาย'
    else:
        return gender

df['เพศ'] = df['เพศ'].apply(standardize_gender)
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
2,64003,NaN,28,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-01-13,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์
5,64006,กานต์,150,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2023-12-23,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
10,64011,ธีระ,28,ชาย,วิทยาศาสตร์,3.78,NaN,68.0,NaN,2024-01-07,วิทยาศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
18,64019,รัตนา,28,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18,ศิลปศาสตร์
19,64020,ลัดดา,22,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

In [11]:
#จัดการค่าผิดปกติ
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ชาย,วิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.50,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,NaN,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
19,64020,ลัดดา,22,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

In [12]:
df.loc[df['GPA'] < 0, 'GPA'] = np.nan
df.loc[df['GPA'] > 4, 'GPA'] = 4.0
mean_gpa = df['GPA'].mean()
df['GPA'].fillna(mean_gpa, inplace=True)
df['GPA']= df['GPA'].round(2)
df

/tmp/ipython-input-1581386876.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GPA'].fillna(mean_gpa, inplace=True)
/tmp/ipython-input-1581386876.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['GPA'].fillna(mean_gpa, inplace=True)
/tmp/ipython-input-1581386876.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['GPA']= df['GPA'].round(2)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-02-05,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ชาย,วิทยาศาสตร์,3.45,168.0,70.0,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-27,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.00,158.0,48.0,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-03,ศิลปศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,3.45,171.0,NaN,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-08,วิทยาศาสตร์
19,64020,ลัดดา,22,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-06,วิทยาศาสตร์

In [13]:
mean_weight = df['น้ำหนัก_kg'].mean()
df['น้ำหนัก_kg'] = df['น้ำหนัก_kg'].fillna(mean_weight).astype(int)
df

/tmp/ipython-input-3239304738.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['น้ำหนัก_kg'] = df['น้ำหนัก_kg'].fillna(mean_weight).astype(int)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170.0,65,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165.0,58,20.0,2024-02-05,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ชาย,วิทยาศาสตร์,3.45,168.0,70,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52,30.0,2024-01-27,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.00,158.0,48,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,หญิง,ศิลปศาสตร์,2.98,180.0,82,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,ชาย,ศิลปศาสตร์,3.34,163.0,55,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167.0,60,28.0,2024-01-03,ศิลปศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,3.45,171.0,61,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164.0,54,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,หญิง,วิทยาศาสตร์,3.67,162.0,56,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ชาย,วิทยาศาสตร์,3.89,173.0,78,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161.0,50,27.0,2024-01-08,วิทยาศาสตร์
19,64020,ลัดดา,22,ชาย,วิทยาศาสตร์,3.45,168.0,64,23.0,2024-01-06,วิทยาศาสตร์

In [14]:
mean_height = df['ส่วนสูง_cm'].mean()
df['ส่วนสูง_cm'] = df['ส่วนสูง_cm'].fillna(mean_height).astype(int)
df

/tmp/ipython-input-467177524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ส่วนสูง_cm'] = df['ส่วนสูง_cm'].fillna(mean_height).astype(int)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170,65,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165,58,20.0,2024-02-05,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ชาย,วิทยาศาสตร์,3.45,168,70,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,หญิง,วิศวกรรมศาสตร์,3.89,160,52,30.0,2024-01-27,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.00,158,48,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,หญิง,ศิลปศาสตร์,2.98,180,82,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,ชาย,ศิลปศาสตร์,3.34,163,55,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167,60,28.0,2024-01-03,ศิลปศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,3.45,171,61,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169,72,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164,54,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,หญิง,วิทยาศาสตร์,3.67,162,56,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ชาย,วิทยาศาสตร์,3.89,173,78,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,หญิง,วิศวกรรมศาสตร์,3.01,166,62,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161,50,27.0,2024-01-08,วิทยาศาสตร์
19,64020,ลัดดา,22,ชาย,วิทยาศาสตร์,3.45,168,64,23.0,2024-01-06,วิทยาศาสตร์

In [15]:
df_faculty = df[['คณะ', 'รหัสนักศึกษา']]
df_encoded = pd.get_dummies(df_faculty,columns=['คณะ'])
df_encoded

    รหัสนักศึกษา  คณะ_วิทยาศาสตร์  คณะ_วิศวกรรมศาสตร์  คณะ_ศิลปศาสตร์
0          64001             True               False           False
1          64002             True               False           False
3          64004             True               False           False
4          64005            False                True           False
6          64007            False                True           False
7          64008            False               False            True
8          64009            False               False            True
9          64010            False               False            True
11         64012             True               False           False
12         64013            False                True           False
13         64014            False               False            True
14         64015             True               False           False
15         64016             True               False           False
16         64017            False                True           False
17         64018             True               False           False
19         64020             True               False           False

In [16]:
df_before
#vs
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_มาตรฐาน
0,64001,สมชาย,20,ชาย,วิทยาศาสตร์,3.21,170,65,15.0,2024-01-23,วิทยาศาสตร์
1,64002,สมหญิง,21,หญิง,วิทยาศาสตร์,3.45,165,58,20.0,2024-02-05,วิทยาศาสตร์
3,64004,สมศักดิ์,22,ชาย,วิทยาศาสตร์,3.45,168,70,10.0,2023-12-30,วิทยาศาสตร์
4,64005,สมใจ,19,หญิง,วิศวกรรมศาสตร์,3.89,160,52,30.0,2024-01-27,วิศวกรรมศาสตร์
6,64007,กิตติ,21,หญิง,วิศวกรรมศาสตร์,4.00,158,48,35.0,2024-01-05,วิศวกรรมศาสตร์
7,64008,จิรา,20,หญิง,ศิลปศาสตร์,2.98,180,82,18.0,2024-01-23,ศิลปศาสตร์
8,64009,ชนาธิป,23,ชาย,ศิลปศาสตร์,3.34,163,55,22.0,2024-02-11,ศิลปศาสตร์
9,64010,ดารา,21,หญิง,ศิลปศาสตร์,3.56,167,60,28.0,2024-01-03,ศิลปศาสตร์
11,64012,นภา,22,ชาย,วิทยาศาสตร์,3.45,171,61,16.0,2023-12-26,วิทยาศาสตร์
12,64013,บุญมี,20,หญิง,วิศวกรรมศาสตร์,3.23,169,72,24.0,2023-12-26,วิศวกรรมศาสตร์
13,64014,ปรีชา,21,ชาย,ศิลปศาสตร์,3.45,164,54,19.0,2024-01-08,ศิลปศาสตร์
14,64015,พิมพ์,22,หญิง,วิทยาศาสตร์,3.67,162,56,26.0,2024-02-06,วิทยาศาสตร์
15,64016,ภูมิ,19,ชาย,วิทยาศาสตร์,3.89,173,78,14.0,2024-01-20,วิทยาศาสตร์
16,64017,มานี,20,หญิง,วิศวกรรมศาสตร์,3.01,166,62,21.0,2024-01-24,วิศวกรรมศาสตร์
17,64018,ยุพา,21,หญิง,วิทยาศาสตร์,3.23,161,50,27.0,2024-01-08,วิทยาศาสตร์
19,64020,ลัดดา,22,ชาย,วิทยาศาสตร์,3.45,168,64,23.0,2024-01-06,วิทยาศาสตร์

In [17]:
df_feature = df[['รหัสนักศึกษา','GPA']]
df_feature['ผลการเรียน'] = pd.cut(df_feature['GPA'],
                                   bins=[0, 2, 3, 3.5, 4],
                                   labels=['แย่', 'ต่ำ', 'ปกติ', 'ดี'],
                                   include_lowest=True)
df_feature

/tmp/ipython-input-169939513.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_feature['ผลการเรียน'] = pd.cut(df_feature['GPA'],

    รหัสนักศึกษา   GPA ผลการเรียน
0          64001  3.21       ปกติ
1          64002  3.45       ปกติ
3          64004  3.45       ปกติ
4          64005  3.89         ดี
6          64007  4.00         ดี
7          64008  2.98        ต่ำ
8          64009  3.34       ปกติ
9          64010  3.56         ดี
11         64012  3.45       ปกติ
12         64013  3.23       ปกติ
13         64014  3.45       ปกติ
14         64015  3.67         ดี
15         64016  3.89         ดี
16         64017  3.01       ปกติ
17         64018  3.23       ปกติ
19         64020  3.45       ปกติ